{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bagussubagja.flutter_liveness_detection_randomized_plugin.flutter_liveness_detection_randomized_plugin",
    "module": "flutter_liveness_detection_randomized_plugin_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_liveness_detection_randomized_plugin_release-1.0.aar",
          "url": "flutter_liveness_detection_randomized_plugin_release-1.0.aar",
          "size": 2691,
          "sha512": "3a8b7bc475b1a823048c5b44f6959046eefa0155f97ed3ecca8333d0d72a02f8a987a98a2544bc668f0ad483f81fc1769724e9d203843b5f99bb7ed2ce702700",
          "sha256": "7b55a4080460018d2f331ad0797ea9ed05ca3fe61334cd4f522cfaf3730f1792",
          "sha1": "e68a9e604b471a93066e2feec37ddb5d57823d5c",
          "md5": "9ec92ee65332cb9c1a539ae9c2474591"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        },
        {
          "group": "com.google_mlkit_face_detection",
          "module": "google_mlkit_face_detection_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_liveness_detection_randomized_plugin_release-1.0.aar",
          "url": "flutter_liveness_detection_randomized_plugin_release-1.0.aar",
          "size": 2691,
          "sha512": "3a8b7bc475b1a823048c5b44f6959046eefa0155f97ed3ecca8333d0d72a02f8a987a98a2544bc668f0ad483f81fc1769724e9d203843b5f99bb7ed2ce702700",
          "sha256": "7b55a4080460018d2f331ad0797ea9ed05ca3fe61334cd4f522cfaf3730f1792",
          "sha1": "e68a9e604b471a93066e2feec37ddb5d57823d5c",
          "md5": "9ec92ee65332cb9c1a539ae9c2474591"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_liveness_detection_randomized_plugin_release-1.0-sources.jar",
          "url": "flutter_liveness_detection_randomized_plugin_release-1.0-sources.jar",
          "size": 1882,
          "sha512": "c9ed259360277a641b06725975b57feb67d6b543c7188a645f8fda4de3a354b4c73addd2ab7a04e09975d10434fb548eacd26e9bed735ff743dd596ea09e6f85",
          "sha256": "6879def171989bfa001b27789c573ec28fde58039202343674f867a8a827b7e1",
          "sha1": "4a6ef6caefdd111935f865ee9088ccff91bac5ed",
          "md5": "e73afd84dbdc69968031953f48a0329a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_liveness_detection_randomized_plugin_release-1.0-javadoc.jar",
          "url": "flutter_liveness_detection_randomized_plugin_release-1.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
