{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.network_info",
    "module": "network_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus_release-1.0.aar",
          "url": "network_info_plus_release-1.0.aar",
          "size": 9714,
          "sha512": "62caa1ee35729cd6c475727a1f2e145cc2644c0e1acff4aade2005c8adcec2da4129b556a37cdf8681dfa7d7280cc71d3c95e1d3dc2babc03415fab58ac6cd52",
          "sha256": "b33588e172ed7ade023fc4f6fce542d73df849336cc4be650f6f4b9483c9560c",
          "sha1": "58d999fc3441978589d49ef5f14333afc1d8965e",
          "md5": "6e4c41b63766b13173a1dbcee2625b9a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus_release-1.0.aar",
          "url": "network_info_plus_release-1.0.aar",
          "size": 9714,
          "sha512": "62caa1ee35729cd6c475727a1f2e145cc2644c0e1acff4aade2005c8adcec2da4129b556a37cdf8681dfa7d7280cc71d3c95e1d3dc2babc03415fab58ac6cd52",
          "sha256": "b33588e172ed7ade023fc4f6fce542d73df849336cc4be650f6f4b9483c9560c",
          "sha1": "58d999fc3441978589d49ef5f14333afc1d8965e",
          "md5": "6e4c41b63766b13173a1dbcee2625b9a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "network_info_plus_release-1.0-sources.jar",
          "url": "network_info_plus_release-1.0-sources.jar",
          "size": 3679,
          "sha512": "b198775219da012224ea397889a5f6a942588804251e181f98a05e34775cdb57e61df0304ae7cf78879069bb8a5898791a1c113e62c80503491e0d0a4945186c",
          "sha256": "4ae0e718b56cab5398eecbb570daef92720b96e7e2e29e1b1515b318e61c1b2d",
          "sha1": "b120b77ed25123ad5e87079e03297ded118c833d",
          "md5": "79b01a5ca1cfccce57b01928c855e190"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "network_info_plus_release-1.0-javadoc.jar",
          "url": "network_info_plus_release-1.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
