{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.0.aar",
          "url": "image_picker_android_release-1.0.aar",
          "size": 69583,
          "sha512": "a0f145c420ad0e41a111d92cb9b153df86b03e9b72e0befa8105fb38101f9b9ca4f8146a8c2ea0b0eeb29c918eef7c0cb1d2a5a7055c11f294e882d7eff0d9b5",
          "sha256": "df1ea1e674bae6b21c56aee6ef3193c72b2d18b9b4b2bb6fba3b1e730ff64268",
          "sha1": "0afad8808622e481d506a4aa327f994a0728e325",
          "md5": "18af53fa04a647a63285ac2537bed3f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.0.aar",
          "url": "image_picker_android_release-1.0.aar",
          "size": 69583,
          "sha512": "a0f145c420ad0e41a111d92cb9b153df86b03e9b72e0befa8105fb38101f9b9ca4f8146a8c2ea0b0eeb29c918eef7c0cb1d2a5a7055c11f294e882d7eff0d9b5",
          "sha256": "df1ea1e674bae6b21c56aee6ef3193c72b2d18b9b4b2bb6fba3b1e730ff64268",
          "sha1": "0afad8808622e481d506a4aa327f994a0728e325",
          "md5": "18af53fa04a647a63285ac2537bed3f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-1.0-sources.jar",
          "url": "image_picker_android_release-1.0-sources.jar",
          "size": 26716,
          "sha512": "f140da762265150c64a4187e1b9adf969983e4b5d570210038ce434cb03e8e5ac8bdf729a3c4a52ed13cbfe381cf7eb50633e319ceb5028ec2a8493ac351c98d",
          "sha256": "712d1dfa112f9ee2799f7439cb827e066271d66acb679fa4afea122863deb43e",
          "sha1": "a5e6fa92877cc6479365167e9891b9b9cc1a67ec",
          "md5": "60bb9390cb7e6ebab4e666e1d9d87b06"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-1.0-javadoc.jar",
          "url": "image_picker_android_release-1.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
