{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_release-1.0.aar",
          "url": "camera_android_release-1.0.aar",
          "size": 161418,
          "sha512": "39b29c6e9f8ec0fd06370264911332c58048e915f94e916f59b9422bf0214346e17a6fa5924f8086f83de642443a9a4f4fc3bce82812ab5fb696a7f7ff697fe3",
          "sha256": "422f31275c36785bd32719739efca52f1f86181e5545ea19a31d6f4cd113f6a0",
          "sha1": "49c99b661b82bff27f5075bb5714058ce237212b",
          "md5": "2849873e65ba293214c5a0bbda9c8df1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_release-1.0.aar",
          "url": "camera_android_release-1.0.aar",
          "size": 161418,
          "sha512": "39b29c6e9f8ec0fd06370264911332c58048e915f94e916f59b9422bf0214346e17a6fa5924f8086f83de642443a9a4f4fc3bce82812ab5fb696a7f7ff697fe3",
          "sha256": "422f31275c36785bd32719739efca52f1f86181e5545ea19a31d6f4cd113f6a0",
          "sha1": "49c99b661b82bff27f5075bb5714058ce237212b",
          "md5": "2849873e65ba293214c5a0bbda9c8df1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_release-1.0-sources.jar",
          "url": "camera_android_release-1.0-sources.jar",
          "size": 86865,
          "sha512": "6b87feb28e2e2c4c01ffdadd4c9f446209f3b21fed71885aa7de847ffa576cdf00aafc37cbe82c236625959ad51b632d6d7f8e842d781fa3b13699557b414e38",
          "sha256": "ea08a47a1650fa9f96eaa98cb2b700252aedf3aee570a225c22fa15106e451b4",
          "sha1": "435b5826df5b2c0e1af36f29c5f3c422d11c0f65",
          "md5": "4919270377f3fcd37ed6684c275cc071"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_release-1.0-javadoc.jar",
          "url": "camera_android_release-1.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
