{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 22530,
          "sha512": "e55bf9629261b14ca1c4648eb7916008967d9a0583fa2cde1eafdfdceee6f69d208d9e02d4f4607590bf58c4576e1dbc9fcca004c7aa594983878103aa1b3ce8",
          "sha256": "b6584332cfeb30b4d57a4638d3956287f729daf1849eadb2cbb23a8f879e14cb",
          "sha1": "ed2bee61363a632001b1357592642a6418752e63",
          "md5": "89d6e9e04c821c3bc1864644463d8fb6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 22530,
          "sha512": "e55bf9629261b14ca1c4648eb7916008967d9a0583fa2cde1eafdfdceee6f69d208d9e02d4f4607590bf58c4576e1dbc9fcca004c7aa594983878103aa1b3ce8",
          "sha256": "b6584332cfeb30b4d57a4638d3956287f729daf1849eadb2cbb23a8f879e14cb",
          "sha1": "ed2bee61363a632001b1357592642a6418752e63",
          "md5": "89d6e9e04c821c3bc1864644463d8fb6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_release-1.0-sources.jar",
          "url": "url_launcher_android_release-1.0-sources.jar",
          "size": 9404,
          "sha512": "5ac088da042502a3f5c39f955abf092c6ed490da35464d60eef45dfe1262eaa3143a53d77fbc218d037582b780c5421fdaf8847482847de8b1bffa8ceaf3468e",
          "sha256": "fc09a1ed942bde1578570cc2f2198e7e9b51c87bfa35bb88eb9343b3fc7d83c3",
          "sha1": "7a87e8d621aa50c862331ee6827305b6c76c57fd",
          "md5": "1266bbfa8f2588435497db7b9ffe2c0d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_release-1.0-javadoc.jar",
          "url": "url_launcher_android_release-1.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
